---
- name: Packages
  ansible.builtin.package:
    name:
      - dnsutils
      - iperf3
      - net-tools
    state: present

- name: Cloudflare apt key
  ansible.builtin.apt_key:
    url: https://pkg.cloudflareclient.com/pubkey.gpg
    keyring: /etc/apt/trusted.gpg.d/cloudflare-warp-archive-keyring.gpg

- name: Cloudflare apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ {{ ansible_distribution_release }} main" # noqa: yaml[line-length]
  register: cfrepo

- name: Update sources
  ansible.builtin.apt:
    update_cache: true
  when: cfrepo.changed # noqa: no-handler

- name: Cloudflare WARP
  ansible.builtin.apt:
    name: cloudflare-warp

- name: Enable IP forwarding for WARP
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true

- name: No DigitalOcean DNS config file
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d/DigitalOcean.conf
    state: absent
  notify:
    - Restart systemd-resolved

- name: Cloudflare WARP DNS
  ansible.builtin.copy:
    src: warp.conf
    dest: /etc/systemd/resolved.conf.d/warp.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart systemd-resolved
