---
- name: Add ansible group.
  ansible.builtin.group:
    name: ansible
    state: present
    system: true

- name: Add ansible user.
  ansible.builtin.user:
    name: ansible
    group: ansible
    create_home: true
    home: /home/ansible
    shell: /sbin/nologin
    state: present
    system: true
    umask: "077"

- name: Set home directory ownership recursively.
  ansible.builtin.file:
    path: /home/ansible
    state: directory
    owner: ansible
    group: ansible
    recurse: true

- name: Set restrictive permissions on home directory.
  ansible.builtin.file:
    path: /home/ansible
    state: directory
    mode: "0700"
