---
name: Build dev container

on:
  pull_request:
    paths:
      - ".devcontainer/**"
      - ".github/workflows/build-devcontainer.yml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build dev container
    runs-on: ubuntu-latest

    permissions:
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: docker image build --tag "$GITHUB_SHA" .devcontainer/

      - name: Install hooks
        run: >-
          docker container run
          --mount type=bind,source="$GITHUB_WORKSPACE",target=/src
          --workdir /src
          "$GITHUB_SHA"
          /bin/bash -c "git config --global --add safe.directory /src; pre-commit install --install-hooks"
