---
name: Lint

on:
  push:
    branches-ignore:
      - main
  pull_request: null

permissions:
  contents: read

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
