---
name: Test systemd

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-playbook:
    name: Test systemd
    runs-on: ubuntu-22.04

    permissions:
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check enabled units
        run: systemctl --no-pager list-unit-files --state=enabled

      - name: Check sudoers
        run: sudo cat /etc/sudoers

      - name: Check sudoers.d
        run: sudo find /etc/sudoers.d -type f -exec cat {} \;
